#!/bin/bash

rm -rf INSTALL
rm -rf Makefile
rm -rf Makefile.in
rm -rf aclocal.m4
rm -rf autom4te.cache/
rm -rf config.log
rm -rf config.status
rm -rf configure
rm -rf include/stamp-h1
rm -rf install-sh
rm -rf libcmfs/.deps/
rm -rf libcmfs/Makefile
rm -rf libcmfs/Makefile.in
rm -rf libcmfs/*.o
rm -rf libcmfs/libcmfs.a
rm -rf libcmfs/cmfs_err.c
rm -rf libcmfs/cmfs_err.h
rm -rf missing
rm -rf mkfs.cmfs/.deps/
rm -rf mkfs.cmfs/Makefile
rm -rf mkfs.cmfs/Makefile.in
rm -rf mkfs.cmfs/*.o
rm -rf mkfs.cmfs/mkfs.cmfs
rm -rf misc/.deps
rm -rf misc/Makefile
rm -rf misc/Makefile.in
rm -rf misc/member_offset
rm -rf misc/member_offset.o
